# Generated by Django 6.0.2 on 2026-02-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('LAB_TECH', 'Lab Technician'), ('ADMIN', 'Admin')], default='PATIENT', help_text='User role for access control', max_length=20),
        ),
    ]
