# Generated by Django 6.0.1 on 2026-02-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('LAB_TECH', 'Lab Technician'), ('HOSPITAL_ADMIN', 'Hospital Admin'), ('ADMIN', 'Admin')], default='PATIENT', help_text='User role for access control', max_length=20),
        ),
    ]
