# Generated by Django 6.0.1 on 2026-02-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(choices=[('VIEW_PROFILE', 'View Profile'), ('VIEW_RECORDS', 'View Records'), ('UPLOAD_RECORD', 'Upload Record'), ('LOGIN', 'Login'), ('CREATE_CONSULTATION', 'Create Consultation'), ('UPLOAD_DOCUMENT', 'Upload Document'), ('GRANT_ACCESS', 'Grant Access'), ('REVOKE_ACCESS', 'Revoke Access'), ('CREATE_HEALTH_ID', 'Create Health ID')], max_length=20),
        ),
    ]
