# Generated by Django 6.0.1 on 2026-02-06 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Known allergies'),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AddField(
            model_name='patient',
            name='chronic_conditions',
            field=models.TextField(blank=True, help_text='Ongoing health conditions'),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('can_grant_access', models.BooleanField(default=True, help_text='Can share OTP on behalf of patient in emergencies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='OldPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateField()),
                ('doctor_name', models.CharField(blank=True, max_length=100)),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('symptoms', models.TextField(help_text='Symptoms reported at the time')),
                ('diagnosis', models.TextField(blank=True)),
                ('medicines', models.JSONField(default=list, help_text="List of medicines with dosage, e.g., [{'name': 'Paracetamol', 'dosage': '500mg', 'frequency': 'twice daily'}]")),
                ('insights', models.TextField(blank=True, help_text="Doctor's notes/insights")),
                ('file', models.FileField(blank=True, null=True, upload_to='old_prescriptions/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_prescriptions', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prescription_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('REPORT', 'Medical Report'), ('INSURANCE', 'Insurance Document'), ('ID_PROOF', 'ID Proof'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='patient_documents/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SharingPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('QR_QUICK', 'QR Quick Preview (24hr)'), ('OTP_FULL', 'OTP Full Access'), ('EMERGENCY', 'Emergency Access')], default='QR_QUICK', max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('can_view_records', models.BooleanField(default=True)),
                ('can_view_documents', models.BooleanField(default=False)),
                ('can_add_records', models.BooleanField(default=False, help_text='Only for OTP_FULL access')),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_permissions', to='doctors.doctor')),
                ('granted_by', models.ForeignKey(help_text='Patient or Emergency Contact who granted access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_permissions', to='patients.patient')),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
    ]
