# Generated by Django 6.0.2 on 2026-02-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_otprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='organ_donor',
            field=models.BooleanField(default=False, help_text='Willing to donate organs'),
        ),
    ]
