# Generated by Django 6.0.1 on 2026-02-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_organ_donor_verified',
            field=models.BooleanField(default=False, help_text='Admin verification status'),
        ),
        migrations.AddField(
            model_name='patient',
            name='organ_donor_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason if verification failed'),
        ),
    ]
