# Generated by Django 6.0.1 on 2026-02-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_is_organ_donor_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='organ_donor_document',
            field=models.FileField(blank=True, null=True, upload_to='organ_donor_declarations/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='organ_donor_status',
            field=models.CharField(choices=[('OFF', 'Not Registered'), ('PENDING_UPLOAD', 'Pending Upload'), ('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='OFF', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='organ_donor_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='organ_donor_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
