# Generated by Django 6.0.1 on 2026-02-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_organ_donor_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_organ_donor_verified',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='organ_donor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='organ_donor_document',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='organ_donor_rejection_reason',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='organ_donor_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='organ_donor_submitted_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='organ_donor_verified_at',
        ),
    ]
