# Generated by Django 6.0.1 on 2026-03-22 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_patient_is_organ_donor_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otprequest',
            name='delivery_method',
            field=models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('DASHBOARD', 'Dashboard')], default='DASHBOARD', max_length=20),
        ),
        migrations.AddField(
            model_name='otprequest',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otprequest',
            name='verifier_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_requests_to_verify', to='patients.emergencycontact'),
        ),
        migrations.AddField(
            model_name='otprequest',
            name='verifier_type',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('EMERGENCY_CONTACT', 'Emergency Contact')], default='PATIENT', max_length=20),
        ),
    ]
