# Generated by Django 6.0.1 on 2026-04-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_otprequest_attempts_otprequest_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='delivery_method',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('DASHBOARD', 'Dashboard')], default='DASHBOARD', max_length=20),
        ),
    ]
