# Generated by Django 4.2 on 2026-04-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_emergencycontact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oldprescription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oldprescription',
            name='medicines',
            field=models.TextField(blank=True, help_text='List of medicines and dosages'),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sharingpermission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
