# Generated by Django 4.2 on 2026-04-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_emergencycontact_id_alter_oldprescription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldprescription',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Symptoms reported at the time'),
        ),
    ]
