# Generated by Django 6.0.1 on 2026-05-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_oldprescription_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='allow_emergency_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='preferred_otp_method',
            field=models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('BOTH', 'Both')], default='SMS', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='allow_public_qr_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_snapshot_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='show_all_emergency_contacts',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oldprescription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sharingpermission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
