# Generated by Django 6.0.1 on 2026-05-19 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_hospital_rejection_reason'),
        ('patients', '0013_emergencycontact_allow_emergency_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_requests', to='doctors.doctor'),
        ),
    ]
