# Generated by Django 6.0.2 on 2026-02-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='medicines',
            field=models.JSONField(blank=True, default=list, help_text="List of medicines, e.g., [{'name': 'Paracetamol', 'dosage': '500mg', 'frequency': 'twice daily'}]"),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='prescription',
            field=models.TextField(blank=True, help_text='Legacy text prescription or general notes'),
        ),
    ]
