# Generated by Django 6.0.2 on 2026-02-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='degree_certificate',
            field=models.FileField(blank=True, null=True, upload_to='doctor_documents/degrees/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='identity_proof',
            field=models.FileField(blank=True, null=True, upload_to='doctor_documents/ids/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='issuing_medical_council',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='doctor_documents/licenses/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
