# Generated by Django 6.0.2 on 2026-02-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_consultation_medicines_and_more'),
        ('doctors', '0003_doctor_degree_certificate_doctor_identity_proof_and_more'),
    ]

    operations = [
    ]
