# Generated by Django 6.0.2 on 2026-02-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_merge_20260219_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
