# Generated by Django 6.0.1 on 2026-02-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_hospitaladmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection, if applicable'),
        ),
    ]
