# Generated by Django 6.0.1 on 2026-02-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_department_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
