# Generated by Django 6.0.1 on 2026-05-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_alter_doctor_contact_number_alter_hospital_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='Blood Pressure in mmHg', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pulse',
            field=models.PositiveIntegerField(blank=True, help_text='Pulse in bpm', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='spo2',
            field=models.PositiveIntegerField(blank=True, help_text='SpO2 in %', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temperature in °F', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
    ]
