# Generated by Django 6.0.1 on 2026-02-20 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_hospitaladmin'),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtechnician',
            name='hospital',
        ),
        migrations.CreateModel(
            name='DiagnosticLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('accreditation_number', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField(default=False, help_text='Set to True after admin approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs', to='doctors.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='labtechnician',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicians', to='labs.diagnosticlab'),
        ),
    ]
