# Generated by Django 6.0.1 on 2026-02-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_remove_labtechnician_hospital_diagnosticlab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticlab',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason if verification failed'),
        ),
        migrations.AddField(
            model_name='labtechnician',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason if verification failed'),
        ),
    ]
