# Generated by Django 6.0.1 on 2026-05-13 17:24

from django.db import migrations


def populate_lab_tests(apps, schema_editor):
    LabTest = apps.get_model('labs', 'LabTest')
    tests_data = [
        (1, 'Complete Blood Count (CBC)', 'CBC'),
        (2, 'Lipid Profile', 'LIPID'),
        (3, 'Thyroid Function Test', 'TFT'),
        (4, 'Urinalysis', 'URINE'),
        (5, 'COVID-19 RT-PCR', 'RTPCR'),
    ]
    for tid, name, code in tests_data:
        LabTest.objects.get_or_create(id=tid, defaults={'name': name, 'code': code})

def reverse_lab_tests(apps, schema_editor):
    pass # No need to delete them as they might be used

class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_diagnosticlab_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_lab_tests, reverse_lab_tests)
    ]
