# Generated by Django 6.0.1 on 2026-05-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_populate_default_lab_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticlab',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
